%% Example for a metadata file
% has to be populated with the necessary key-value pairs
function metadata = getMetaData()
%% information about the measurements
    metadata = struct( ...
        'm1', struct( ...
            'filename',  'Brillouin', ...
            'comment',   '', ...
            'sample',    'wtwik-sham-01', ...
            'type',      'sham', ...
            'treatment', 'DMSO', ...
            'dpf',       4.0, ...
            'viable',    'alive', ...
            'valid',     'true' ...
        ), ...
        'm2', struct( ...
            'filename',  'Brillouin-0', ...
            'comment',   '', ...
            'sample',    'wtwik-sham-02', ...
            'type',      'sham', ...
            'treatment', 'DMSO', ...
            'dpf',       4.0, ...
            'viable',    'alive', ...
            'valid',     'true' ...
        ), ...
        'm3', struct( ...
            'filename',  'Brillouin-1', ...
            'comment',   '', ...
            'sample',    'wtwik-sham-03', ...
            'type',      'sham', ...
            'treatment', 'DMSO', ...
            'dpf',       4.0, ...
            'viable',    'alive', ...
            'valid',     'true' ...
        ) ...
    );
end