function [y] = lorentz4(x, sa, sb, sc, sd, wa, wb, wc, wd, Ba, Bb, Bc, Bd)
% LORENTZ4 model for a lorentz function with 4 peaks

    y = Ba * ((wa/2).^2) ./ ((x - sa).^2 + (wa/2).^2) + ...
        Bb * ((wb/2).^2) ./ ((x - sb).^2 + (wb/2).^2) + ...
        Bc * ((wc/2).^2) ./ ((x - sc).^2 + (wc/2).^2) + ...
        Bd * ((wd/2).^2) ./ ((x - sd).^2 + (wd/2).^2);
end