classdef Model < handle
%% MODEL

    % observable properties, listeners are notified on change
    properties (SetObservable = true)
        file;       % handle to the H5BM file
        filename;   % name of the H5BM file
        pp;         % path to the program
        results;    % results of the evaluation
        settings;   % settings used for evaluation
        handles;    % structure with handles which need to be set dynamically
    end

    methods
        function obj = Model()
            obj.filename = [];
            obj.file = [];
            obj.results = struct( ...
                'brillouinPosition', NaN, ...
                'brillouinWidth', NaN, ...
                'intensity', NaN ...
            );
            obj.settings = struct( ...
                'extraction', struct( ...
                    'autoscale', false, ...
                    'floor', 100, ...
                    'cap', 500, ...
                    'width', 3, ...         % [pix] width of the extracted spectrum
                    'peaks', struct( ...    % position of the peaks for localising the spectrum
                        'x', [], ...        % [pix] x-position
                        'y', [] ...         % [pix] y-position
                    ), ...
                    'extractionAxis', 'y', ...          % {'x', 'y', 'f'} axis along which the extraction is performed
                    'interpolationDirection', 'f', ...   % {'x', 'y', 'f'} direction of the interpolation
                    'circleStart', NaN, ...
                    'circleFit', NaN, ...
                    'r0', NaN, ...
                    'x0', NaN, ...
                    'y0', NaN, ...
                    'interpolationCenters', struct( ...
                        'x', [], ...        % [pix] x-position
                        'y', [] ...         % [pix] y-position
                    ), ...
                    'interpolationBorders', struct( ...
                        'x', [], ...        % [pix] x-position
                        'y', [] ...         % [pix] y-position
                    ), ...
                    'interpolationPositions', struct( ...
                        'x', [], ...        % [pix] x-position
                        'y', [] ...         % [pix] y-position
                    ) ...
                ), ...
                'fitting', struct( ...
                    'fwhm', 5, ...          % [pix] initial value for the FWHM of the Brillouin peak
                    'gap', 10 ...           % [pix] minimum x and y distance of maxima to the edges of the image
                ) ...
            );
            obj.handles = struct( ...
            );
        end
    end
end